apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: newtest2sscx
  namespace: sdouglas1
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-application
        appstudio.openshift.io/component: newtest2sscx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: newtest2sscx-
      labels:
        appstudio.openshift.io/application: test-application
        appstudio.openshift.io/component: newtest2sscx
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: sdouglas1
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/hacbs-test-project
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:sdouglas1-newtest2sscx-$(tt.params.git-revision)
      - name: revision
        value: b366d7dc4d9a98153895faf3145af1c43a68ef75
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: java-builder
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
